spring:
  application:
    name: authservice

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/sip_agent_portal?user=root
    username: root
    password: root

server:
  port: 8081


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
